### ISSUE TITLE
add "can't use hex codes" to readme?

### ISSUE THREAD

**Issue by skilfullycurled** [fjenett/coffeescript-mode-processing#19]
Hello again!  Long time, no issue.

Someone on the Processing forums (named GoToLoop) realized that it is not possible to use hex codes.  Presumably this is because the hash is a comment in CS?  Could be a good update to the readme if you have a chance (and if that is correct, of course).  I mainly use RGB but I suppose there will be others who like hex.

Hope alls been well!

**Comment by fjenett** [comment]
Updated readme, thanks
